/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author liont
 */
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Radio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CiPerimetro = new javax.swing.JButton();
        CiArea = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CuArea = new javax.swing.JButton();
        CuLado = new javax.swing.JTextField();
        CuPeri = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BaRectan = new javax.swing.JTextField();
        RePerimetro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        HRectan = new javax.swing.JTextField();
        ReArea = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TriArea = new javax.swing.JButton();
        TriBase = new javax.swing.JTextField();
        TriPerimetro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TriH = new javax.swing.JTextField();
        TypeTri = new javax.swing.JButton();
        Type = new javax.swing.JTextField();
        Hipotenusa = new javax.swing.JTextField();
        TypeTri1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        RoPeri = new javax.swing.JButton();
        DMenor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RoArea = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        DMayor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        RLado = new javax.swing.JTextField();
        TrapArea = new javax.swing.JButton();
        TrapPerimetro = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        BaseMayor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TrapLado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        BaseMenor = new javax.swing.JTextField();
        TrapH = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Clean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Circulo");
        jLabel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                jLabel1AncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        jLabel5.setText("Digite Radio");

        jLabel6.setText("Ejercicios Figuras Geometricas");

        CiPerimetro.setText("Calcular Perimetro");
        CiPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiPerimetroActionPerformed(evt);
            }
        });

        CiArea.setText("Calcular Area");
        CiArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CiArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CiPerimetro)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(359, 359, 359))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CiPerimetro)
                    .addComponent(CiArea))
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel3.setText("Cuadrado");

        CuArea.setText("Calcular Area");
        CuArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuAreaActionPerformed(evt);
            }
        });

        CuPeri.setText("Calcular Perimetro");
        CuPeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuPeriActionPerformed(evt);
            }
        });

        jLabel7.setText("Digite Lado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addComponent(CuLado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CuArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CuPeri)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(CuLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CuPeri)
                        .addComponent(CuArea))
                    .addComponent(jLabel3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        jLabel8.setText("Rectangulo");

        jLabel9.setText("Digite Base");

        RePerimetro.setText("Calcular Perimetro");
        RePerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RePerimetroActionPerformed(evt);
            }
        });

        jLabel10.setText("Digite Altura");

        HRectan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRectanActionPerformed(evt);
            }
        });

        ReArea.setText("Calcular Area");
        ReArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaRectan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(HRectan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RePerimetro)
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(BaRectan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RePerimetro)
                    .addComponent(jLabel10)
                    .addComponent(HRectan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReArea))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));

        jLabel11.setText("Triangulo");

        jLabel12.setText("Digite Base");

        TriArea.setText("Calcular Area");
        TriArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriAreaActionPerformed(evt);
            }
        });

        TriPerimetro.setText("Calcular Perimetro");
        TriPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriPerimetroActionPerformed(evt);
            }
        });

        jLabel13.setText("Digite Altura");

        TypeTri.setText("Hipotenusa");
        TypeTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTriActionPerformed(evt);
            }
        });

        TypeTri1.setText(" Tipo de Triangulo");
        TypeTri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTri1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Los resultados de areas y perimetros de este programa");

        jLabel22.setText("se expresan en cm^2 y cm respectivamente ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TriBase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel13))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel22)))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(TriH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TriArea)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TypeTri1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TypeTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TriPerimetro)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(TriBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TriPerimetro)
                    .addComponent(TriArea)
                    .addComponent(jLabel13)
                    .addComponent(TriH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypeTri1)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeTri)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        RoPeri.setText("Calcular Perimetro");
        RoPeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoPeriActionPerformed(evt);
            }
        });

        jLabel4.setText("Rombo");

        jLabel14.setText("Digite Diagonal Menor ");

        RoArea.setText("Calcular Area");
        RoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoAreaActionPerformed(evt);
            }
        });

        jLabel15.setText("Digite Diagonal Menor ");

        jLabel16.setText("Digite Lado ");

        TrapArea.setText("Calcular Area");
        TrapArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapAreaActionPerformed(evt);
            }
        });

        TrapPerimetro.setText("Calcular Perimetro");
        TrapPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapPerimetroActionPerformed(evt);
            }
        });

        jLabel17.setText("Digite Mayor Menor ");

        BaseMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseMayorActionPerformed(evt);
            }
        });

        jLabel18.setText("Digite Lado ");

        jLabel19.setText("Trapecio");

        jLabel20.setText("Digite Base  Menor ");

        BaseMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseMenorActionPerformed(evt);
            }
        });

        jLabel21.setText("Digite Altura ");

        Clean.setText("Limpiar Todos Los Campos");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(44, 44, 44)
                                .addComponent(DMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel14)
                                .addGap(44, 44, 44)
                                .addComponent(DMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(44, 44, 44)
                                .addComponent(RLado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RoArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RoPeri)
                                .addGap(83, 83, 83))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(44, 44, 44)
                                .addComponent(BaseMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel20)
                                .addGap(44, 44, 44)
                                .addComponent(BaseMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TrapLado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(30, 30, 30)
                                .addComponent(TrapH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TrapArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrapPerimetro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Clean)
                                .addGap(57, 57, 57))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(DMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoPeri)
                    .addComponent(RoArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(DMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(RLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(BaseMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrapPerimetro)
                    .addComponent(TrapArea)
                    .addComponent(jLabel18)
                    .addComponent(TrapLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(BaseMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(TrapH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clean))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorMoved

    private void CiPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiPerimetroActionPerformed
        // TODO add your handling code here:
        try { 
        Circulo CirculoY = new Circulo(Double.parseDouble(Radio.getText()));
        JOptionPane.showMessageDialog(null, "El perimetro del circulo es: " + String.valueOf(CirculoY.CalcularP()));      
       }catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_CiPerimetroActionPerformed

    private void CiAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiAreaActionPerformed
        // TODO add your handling code here:
        
        try { 
        Circulo CirculoX = new Circulo(Double.parseDouble(Radio.getText()));
        JOptionPane.showMessageDialog(null, "El area del circulo es: " + String.valueOf(CirculoX.CalcularA()));       
       }catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

        
    }//GEN-LAST:event_CiAreaActionPerformed

    private void RePerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RePerimetroActionPerformed
        // TODO add your handling code here:
        
        try {         Rectangulo RectanguloA = new Rectangulo(Double.parseDouble(BaRectan.getText()),Double.parseDouble(HRectan.getText()));
        JOptionPane.showMessageDialog(null, "El perimetro del rectangulo es: " + String.valueOf(RectanguloA.CalcularP()));
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_RePerimetroActionPerformed

    private void CuPeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuPeriActionPerformed
        // TODO add your handling code here:
        try { 
        Cuadrado CuadradoA = new Cuadrado(Double.parseDouble(CuLado.getText()));
        JOptionPane.showMessageDialog(null, "El perimetro del cuadrado es: " + String.valueOf(CuadradoA.CalcularP()));
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_CuPeriActionPerformed

    private void CuAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuAreaActionPerformed
        // TODO add your handling code here:
        try { 
        Cuadrado CuadradoB = new Cuadrado(Double.parseDouble(CuLado.getText()));
        JOptionPane.showMessageDialog(null, "El area del cuadrado es: " + String.valueOf(CuadradoB.CalcularA()));
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_CuAreaActionPerformed

    private void ReAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReAreaActionPerformed
        try { 
        Rectangulo RectanguloB = new Rectangulo(Double.parseDouble(BaRectan.getText()),Double.parseDouble(HRectan.getText()));
        JOptionPane.showMessageDialog(null, "El area del rectangulo es: " + String.valueOf(RectanguloB.CalcularA()));        
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_ReAreaActionPerformed

    private void RoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoAreaActionPerformed
        // TODO add your handling code here:
        Rombo RomboB = new Rombo(Double.parseDouble(RLado.getText()),Double.parseDouble(DMenor.getText()), Double.parseDouble(DMayor.getText()));
        JOptionPane.showMessageDialog(null, "El area del rombo es: " + String.valueOf(RomboB.CalcularA()));
    }//GEN-LAST:event_RoAreaActionPerformed

    private void RoPeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoPeriActionPerformed
        // TODO add your handling code here:
        try { 
        Rombo RomboA = new Rombo(Double.parseDouble(RLado.getText()),Double.parseDouble(DMenor.getText()), Double.parseDouble(DMayor.getText()));
        JOptionPane.showMessageDialog(null, "El perimetro del rombo es: " + String.valueOf(RomboA.CalcularP()));
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_RoPeriActionPerformed

    private void TrapAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapAreaActionPerformed
        // TODO add your handling code here:
        try { 
         Trapecio TrapecioA = new Trapecio(Double.parseDouble(BaseMenor.getText()), Double.parseDouble(BaseMayor.getText()), 
                Double.parseDouble(TrapLado.getText()), Double.parseDouble(TrapH.getText()));
        JOptionPane.showMessageDialog(null, "El area del Trapecio es: " + String.valueOf(TrapecioA.CalcularA()));       
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

        
    }//GEN-LAST:event_TrapAreaActionPerformed

    private void TrapPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapPerimetroActionPerformed
        // TODO add your handling code here:
        try { 
        Trapecio TrapecioB = new Trapecio(Double.parseDouble(BaseMenor.getText()), Double.parseDouble(BaseMayor.getText()), 
                Double.parseDouble(TrapLado.getText()), Double.parseDouble(TrapH.getText()));
        JOptionPane.showMessageDialog(null, "El perimetro del Trapecio es: " + String.valueOf(TrapecioB.CalcularP()));
       
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_TrapPerimetroActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        BaseMenor.setText("");
        BaseMayor.setText("");
        TrapLado.setText("");
        TrapH.setText("");
        DMayor.setText("");
        DMenor.setText("");
        RLado.setText("");
        TriBase.setText("");
        TriH.setText("");
        Type.setText("");
        Hipotenusa.setText("");
        BaRectan.setText("");
        HRectan.setText("");
        CuLado.setText("");
        Radio.setText("");
    }//GEN-LAST:event_CleanActionPerformed

    private void HRectanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRectanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HRectanActionPerformed

    private void TypeTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTriActionPerformed
        try {         
        Triangulo TrianguloC = new Triangulo(Double.parseDouble(TriBase.getText()),Double.parseDouble(TriH.getText()));
        Hipotenusa.setText(String.valueOf(TrianguloC.calcularHipotenusa()));  
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_TypeTriActionPerformed

    private void TriPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriPerimetroActionPerformed
        // TODO add your handling code here:
        try { 
        Triangulo TrianguloB = new Triangulo(Double.parseDouble(TriBase.getText()),Double.parseDouble(TriH.getText()));
        JOptionPane.showMessageDialog(null, "El perimetro del triangulo es: " + String.valueOf(TrianguloB.CalcularP()));
       
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_TriPerimetroActionPerformed

    private void TriAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriAreaActionPerformed
        // TODO add your handling code here:
        try { 
        Triangulo TrianguloA = new Triangulo(Double.parseDouble(TriBase.getText()),Double.parseDouble(TriH.getText()));
        JOptionPane.showMessageDialog(null, "El area del triangulo es: " + String.valueOf(TrianguloA.CalcularA()));
       
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_TriAreaActionPerformed

    private void TypeTri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTri1ActionPerformed
        try { 
        Triangulo TrianguloC = new Triangulo(Double.parseDouble(TriBase.getText()),Double.parseDouble(TriH.getText()));
        Type.setText(TrianguloC.calcularTipodeTriangulo()); 
       } catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se ha introducido caracteres no validos");}

    }//GEN-LAST:event_TypeTri1ActionPerformed

    private void BaseMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaseMenorActionPerformed

    private void BaseMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaseMayorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BaRectan;
    private javax.swing.JTextField BaseMayor;
    private javax.swing.JTextField BaseMenor;
    private javax.swing.JButton CiArea;
    private javax.swing.JButton CiPerimetro;
    private javax.swing.JButton Clean;
    private javax.swing.JButton CuArea;
    private javax.swing.JTextField CuLado;
    private javax.swing.JButton CuPeri;
    private javax.swing.JTextField DMayor;
    private javax.swing.JTextField DMenor;
    private javax.swing.JTextField HRectan;
    private javax.swing.JTextField Hipotenusa;
    private javax.swing.JTextField RLado;
    private javax.swing.JTextField Radio;
    private javax.swing.JButton ReArea;
    private javax.swing.JButton RePerimetro;
    private javax.swing.JButton RoArea;
    private javax.swing.JButton RoPeri;
    private javax.swing.JButton TrapArea;
    private javax.swing.JTextField TrapH;
    private javax.swing.JTextField TrapLado;
    private javax.swing.JButton TrapPerimetro;
    private javax.swing.JButton TriArea;
    private javax.swing.JTextField TriBase;
    private javax.swing.JTextField TriH;
    private javax.swing.JButton TriPerimetro;
    private javax.swing.JTextField Type;
    private javax.swing.JButton TypeTri;
    private javax.swing.JButton TypeTri1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
